### ISSUE TITLE
Add registering via github OAuth or others

### ISSUE THREAD

**Issue by Chris2011** [Codesee-io/oss-port#214]
I would like to see "login/register with github" or other OAuth providers. That would be good. For OAuth Github it makes more sense, due to the projects, that you want to anaylze for the codesee map.

**Comment by ramonh** [comment]
Interesting proposal! Right now the Port doesn't have any login, as it's a static site.

Or are you perhaps referring to the CodeSee Maps login?

**Comment by Chris2011** [comment]
Yes, I mean the codesee map login. Sry for the confusion. I didn't see a repo for the codesee map itself. I wanted to add a codesee map to my projects mentioned in the PR #207

**Comment by ramonh** [comment]
Thank you for clarifying! I believe we've got some kind of alternative login solution in the roadmap, but I'll have to double check. If it's fine, since that's unrelated to the Port project itself, I'll go ahead and close this. Thanks again!
